incubator/faucet/faucet/Chart.yaml, incubator/faucet/faucet/templates/deployment.yaml
Along the lines of what Lincoln mentioned about security, the version tag for the docker image has been changed from latest to 1.9.6
=> Hard code image version tag

stable/htcondor/htcondor/Chart.yaml, stable/htcondor/htcondor/templates/deployment.yaml
From http://research.cs.wisc.edu/htcondor/manual/v8.6/3_5Configuration_Macros.html#23059 we can supposedly override the `gethostname()` call. Thanks @brianhlin
=> Try to set the hostname from the Downward API

incubator/condor-ce/condor-ce/Chart.yaml, incubator/condor-ce/condor-ce/templates/deployment.yaml
I believe the command I am using to create a symbolic link is overriding the entry point. Removing the command to test.
=> remove command from deployment

stable/htcondor/htcondor/Chart.yaml, stable/htcondor/htcondor/templates/deployment.yaml, stable/htcondor/htcondor/templates/pvc-config-osg.yaml, stable/htcondor/htcondor/templates/pvc-connect.yaml, stable/htcondor/htcondor/templates/pvc-oasis.yaml, stable/htcondor/htcondor/templates/pvc-spt.yaml
Give HTCondor PVCs unique names based on the SLATE instance to prevent conflicts when installing multiple instances.
=> add instance naming to pvcs for htcondor

stable/faucet/faucet/Chart.yaml, stable/faucet/faucet/templates/service.yaml
This change should allow slate instance info to get connection info for faucet.
=> remove prometheus port from faucet service

stable/gridftp/gridftp/Chart.yaml, stable/gridftp/gridftp/README.md, stable/gridftp/gridftp/templates/deployment.yaml, stable/gridftp/gridftp/values.yaml
This both adds use of a PVC as an alternative to a HostPath volume, and also un-mixes-up the ways the paths are used in the deployment.
=> Add support for using a PVC for backing storage

incubator/login-node/images/container-login-node/container-files/etc/supervisord.conf
This fixes the following bug:
```
Traceback (most recent call last):
File "/usr/bin/supervisord", line 9, in <module>
load_entry_point('supervisor==3.1.4', 'console_scripts', 'supervisord')()
File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 366, in main
go(options)
File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 376, in go
d.main()
File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 77, in main
info_messages)
File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1332, in make_logger
self.logger.critical(msg)
File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 287, in critical
self.log(LevelsByName.CRIT, msg, **kw)
File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 293, in log …
```
=> Update supervisord.conf to fix illegal seek

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
- glexec is dropped
- most of the subcluster values aren't reported anymore
- don't need a dummy SE
=> Drop unnecessary osg-configure values

incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
The OSG container is being updated to support a developer mode: https://github.com/opensciencegrid/docker-hosted-ce/pull/12. I added the developer option to the values file for now but I'd be ok taking it out or removing it when we get closer to prod-ready.
=> Add developer mode (SOFTWARE-3906)

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
@matyasselmeci does this look ok to you? I think we agreed that for the Hosted CE case, setting the subcluster name to the resource name was ok.
https://opensciencegrid.atlassian.net/browse/SOFTWARE-3904
=> Consolidate resource name in the Hosted CE helm chart (SOFTWARE-3729)

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
And missed volume specification for the `voms-mapfile`. There really is a lot of repetition in Kubernetes config...
=> Add ability to specify HTCondor-CE configuration (SOFTWARE-3921)

stable/nginx/nginx/Chart.yaml, stable/nginx/nginx/templates/service.yaml
I'm not sure why we didn't run into this before, but without this change I get an error:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service): unknown field "release" in io.k8s.api.core.v1.Service`
Removing the apparently offending property allows the chart to install cleanly.
=> Remove the release from the nginx service, as Kubernetes 1.16 does not seem to like it

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml, stable/htcondor/htcondor/Chart.yaml, stable/htcondor/htcondor/templates/configmap.yaml, stable/htcondor/htcondor/templates/deployment.yaml, stable/htcondor/htcondor/templates/service.yaml, stable/htcondor/htcondor/values.yaml
This is a working PR for functionality for the HostedCE and HTCondor applications.
I've added two modes of functionaltiy here, the first is that if a user has:
```
HTTPLogger:
Enabled: true
```
in their configuration, we will auto-generate a password. The user can retrieve that password via `slate instance logs ...` for the logging-sidecar container within their application.
The second functionality is that if a user prefers to create their own password, this can be done via
```
$ openssl passwd -apr1 <password or interactive input>
$ slate secret  create <secret name> --from-literal=HTPASSWD=<resulting hashed password>
```
And configuring the corresponding `HTTPLogger.Secret` in the Values file.
=> Add HTTPLogger and configurable passwords

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/service.yaml
With the Local traffic policy, kube-proxy on the node that received the traffic sends it only to the service’s pod(s) that are on the same node. There is no “horizontal” traffic flow between nodes.
Because kube-proxy doesn’t need to send traffic between cluster nodes, your pods can see the real source IP address of incoming connections.
The downside of this policy is that incoming traffic only goes to some pods in the service. Pods that aren’t on the current leader node receive no traffic, they are just there as replicas in case a failover is needed.
=> Update HostedCE Service externalTrafficPolicy

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
When clients were contacting the HTCondor-CE, it was giving the daemon's contact info as the private IP address, which a remote client wouldn't be able to resolve. Setting [TCP_FORWARDING_HOST](https://htcondor.readthedocs.io/en/latest/admin-manual/configuration-macros.html#TCP_FORWARDING_HOST) to the requested public IP address forces HTCondor-CE to respond with the daemon's public IP address.
=> Fix daemon contact info

stable/htcondor/htcondor/Chart.yaml, stable/htcondor/htcondor/templates/deployment.yaml
I have no idea how these slipped past the first time.
The first change is because Kubernetes will not set the mode correctly on the startup script. We'll need to have the shell invoke it.
The second change will actually pick out the script and place it into the container, rather than creating a directory containing the script.
=> fixed cmd/args, fixed subpath

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
I'm not sure if the `{{ if .Values.Certificate.Secret }}` stuff will work or if we need to do something like `{{ if .Values.Certificate.Enabled }}` and add `Enabled: false` to the values file
=> Add support for a secret containing a pre-existing host cert and key

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/README.md, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
This patch will allow users of the osg-frontier-squid chart to specify which node they want this application to schedule on.
No node affinity
```
NodeSelection:
Hostname: null
```
Requesting a specific host
```
NodeSelection:
Hostname: node.example.com
```
=> Add node name affinity to osg-frontier-squid

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
@Mansalu @LincolnBryant I'm not sure how the existing host cert/key stuff works without this change. Because with an instance name of `blin-test-ce` I get the following error:
```
Failed to install application osg-hosted-ce: Failed to start application instance with helm:
[exit] 1
[err]: Error: Deployment.apps "osg-hosted-ce-blin-test-ce" is invalid: [spec.template.spec.containers[1].volumeMounts[3].name: Not found: "osg-hosted-ce-blin-test-ce-hostcert", spec.template.spec.containers[1].volumeMounts[4].name: Not found: "osg-hosted-ce-blin-test-ce-hostkey"]
```
=> Use a static name for the host cert/key pair volume name

incubator/open-science-ce/open-science-ce/Chart.yaml, incubator/open-science-ce/open-science-ce/templates/configmap.yaml, incubator/open-science-ce/open-science-ce/templates/deployment.yaml
```
[2020-04-02T15:21:43Z - 2020-04-02T15:22:47Z] FailedMount: MountVolume.SetUp failed for volume "open-science-ce-blin-spool" : configmap "open-science-ce-blin-spool" not found (x8)
[2020-04-02T15:21:44Z - 2020-04-02T15:22:48Z] FailedMount: MountVolume.SetUp failed for volume "blin-condor-configuration" : configmap "blin-condor-configuration" not found (x8)
```
=> Fix Open Science CE event errors

incubator/open-science-ce/open-science-ce/Chart.yaml, incubator/open-science-ce/open-science-ce/templates/configmap.yaml
This gives us a consistent host name across instances
=> Use the external hostname for advertising

incubator/open-science-ce/open-science-ce/Chart.yaml, incubator/open-science-ce/open-science-ce/templates/configmap.yaml
We want to treat jobs submitted to the Open Science CE and routed to
the OSG submit host as payload jobs. Gratia depends on the match
expression to differentiate between payload and pilot jobs.
=> Set the appropriate match expression for payload records

stable/globus-connect-v4/images/globus-connect-v4/supervisord_startup.sh
if `GLOBUS_SERVER` is EMPTY we want to do NOTHING, but if it's got something in it we:
want to comment out the default port IF the `GLOBUS_PORT` is a nonempty string.
=>  i think the logic was inverted here, attempting a fix

stable/globus-connect-v4/globus-connect-v4/Chart.yaml, stable/globus-connect-v4/globus-connect-v4/templates/configmap.yaml
The stupid nesting makes this kinda blow up in a weird way. Need to set `Server =` if the MyProxy section is uncommented, AND if `MyProxy.Server` is uncommented. We should comeup with a better fix later..
=> make the server nonempty

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
With the latest `fresh` container, this change allows the user to provide their own key and get a Let's Encrypt cert. They can then get the cert out of the instance logs and store it in a host cert secret.
Submitting as a draft PR because I'd like to update the `README`.
=> Add the ability to use a pre-generated host key

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/README.md, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
https://opensciencegrid.atlassian.net/browse/SOFTWARE-3960
This is a major refactor of the Hosted CE chart, including:
- The job router doesn't require any additional configuration unless the operator needs to add custom routes, and even then it's simpler to do because the `GridResource` line is set automatically
- Using default `osg-configure` values wherever possible
- VO and grid map files are now lists
- Other various value renaming and restructuring
This PR still needs a chart version update to 3.0.0 and README updates so I'm submitting this as a WIP PR. Also FYI @jdost321 and @mmascher
=> Simplify Hosted CE remote user config (SOFTWARE-3960)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4107
The current container doesn't have a version of `osg-configure` that requires this again but extra values in the `.ini` are ignored and whenever we release the fixed `osg-configure` the app will readily handle it properly.
=> Restore resource group

stable/globus-connect-v4/globus-connect-v4/Chart.yaml, stable/globus-connect-v4/globus-connect-v4/templates/deployment.yaml, stable/globus-connect-v4/globus-connect-v4/values.yaml
The selector's key is now the value of the "NodeSelector:" in the values file. This let's us run multiple Globus endpoints rather than having only one Globus endpoint per cluster
=> updated the Globus node selector

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
OSG Ops ran into issues when testing new deployments:
```
1.0   osg             7/24 08:13 Failed to start GAHP: Agent pid 1953\n/bin/bash: bosco/bin/batch_gahp: No such file or directory\nAgent pid 1953 killed\n
```
The actual path (by default) is `bosco/glite/bin/batch_gahp` so this should fix it.
=> Fix path to look for the batch_gahp/blahp (SOFTWARE-4095)

stable/globus-connect-v4/images/globus-connect-v4/supervisord_startup.sh
This feature allows a user to specify multiple users for the same DN. This is useful for shared accounts and so on.
Here's a self-contained test of the proposed functionality:
```bash
while read -r user pass uid gid comment home shell dns; do
echo "username is: " $user
echo "password is: xxxxxxx"  # we dont watn to print out the password, actually
echo "uid is: " $uid
echo "gid is: " $gid
echo "comment is: " $comment
echo "home is: " $home
echo "shell is: " $shell
echo "X509 DN(s) are: " $dns
if [[ $dns == "" ]]; then
echo "No X509 DN found. Assuming password/MyProxy authentication"
if [[ $pass == "" ]]; then
echo "Password for user $user seems to be empty.. cowardly skipping over this user"
continue
else
echo useradd $user -d $home -u $uid -s $shell -p $pass
fi
else
echo "Adding user …
```
=> Globus multi dn

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml, incubator/jupyter-notebook/jupyter-notebook/templates/service.yaml, incubator/jupyter-notebook/jupyter-notebook/values.yaml
added extra port functionality so we can expose additional ports for middlewares that need inbound connectivity, e.g. parsl
=> allow users to open additional ports in the service object

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
To make use of:
```
RemoteCluster:
SSHBatchMode: False
```
https://github.com/opensciencegrid/docker-hosted-ce/pull/70 needs to be merged and users must pick up the relevant container.
=> Allow the admin to specify the SSH BatchMode (SOFTWARE-4239)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
The GridResource line passes information off to the 'remote_gahp'
script, which doesn't understand the <HOSTNAME>:<PORT> designation.
The Hosted CE containers pre-populate SSH config to specify the
appropriate port for the remote login host so we don't need to retain
the port information.
Fixes/Closes #336
=> Exclude any ":<PORT>" designations from the SSH command

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4291
Corresponding container change in https://github.com/opensciencegrid/docker-hosted-ce/pull/75
Notably, the eyesore if/else may be fixed if you guys are running a new enough version of `helm` and are using `--set-string`: See https://github.com/helm/helm/issues/2848
=> Allow use of the Let's Encrypt staging server (SOFTWARE-4291)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/service.yaml
Adds hostname to an annotation for the Chart's service object.
```
metadata:
annotations:
external-dns.alpha.kubernetes.io/hostname: {{ .Values.Networking.Hostname }} 
```
Requested by @bbockhelm in https://github.com/slateci/slate-catalog/issues/342 
Closes #342
=> Add external-dns annotations to osg-hosted-ce stable chart

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
To support handling of Let's Encrypt certs through
cert-manager (https://cert-manager.io/)
=> Reinstate single host cert/key secret (SOFTWARE-4299)

incubator/open-science-ce/open-science-ce/Chart.yaml, incubator/open-science-ce/open-science-ce/templates/deployment.yaml
We're going to be doing some work to base the Hosted CE container off of the HTCondor-CE container so `fresh` may be dangerous for a bit :)
=> Open Science CE: use htcondor-ce:stable (SOFTWARE-4300)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/README.md
1) Updates documentation to show an example of secret creation for the Logger password.
2) Updates documentation to reflect the changes to networking. Documents new `ServiceType` values field, and discusses HostNetworking.
Closes #238 and #338
=> Improve documentation for osg-hosted-ce stable chart

incubator/cms-xcache/cms-xcache/Chart.yaml, incubator/cms-xcache/cms-xcache/templates/configmap.yaml, incubator/cms-xcache/cms-xcache/templates/deployment.yaml, incubator/cms-xcache/cms-xcache/values.yaml
Users can now specify the cache directories which get unrolled into the config
=> Dynamic cache and meta directory creation in Helm template

incubator/cms-xcache/cms-xcache/Chart.yaml, incubator/cms-xcache/cms-xcache/templates/configmap.yaml, incubator/cms-xcache/cms-xcache/templates/deployment.yaml, incubator/cms-xcache/cms-xcache/values.yaml
OSG's XCache chart prescribes the location where disks ought to be mounted. I've changed the chart to reflect that. See the following:
https://github.com/opensciencegrid/docker-xcache/blob/master/xcache/image-config.d/10-single-host-disk.sh#L3-L21
=> Change disk mount locations

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
1. `MOUNT_UNDER_SCRATCH`: https://opensciencegrid.org/docs/worker-node/using-wn/#for-site-administrators
1. Prescribed `GridDir` location: https://github.com/opensciencegrid/docker-hosted-ce/pull/88/files#diff-60941ebacfc9cf36b6b796d3cfcf856727c6c9249b9d882c1329e76abdcb270dR94
=> Hosted CE fixup comments; hardcode GridDir

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/README.md, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/service.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
*Requires the latest SLATE API only currently available at api-dev.slateci.io*
Adds optional persistent logging to osg-hosted-ce. This feature uses new SLATE volumes to create a long lived volume for logs that can be shared by instances across restarts and updates.
=> [osg-hosted-ce] [incubator] Add (optional) persistent logging

stable/xcache/xcache/templates/deployment.yaml
just an increase in ephemeral storage. xcache logs tend to be big!
=> increased ephemeral storage for xcache

Jenkinsfile
I want to see the contents of the environment when Jenkins pipeline fails to publish catalog builds.
=> Add debug statement to Jenkinsfile pipeline script (printenv)

incubator/cms-xcache/cms-xcache/Chart.yaml, incubator/cms-xcache/cms-xcache/README.md, incubator/cms-xcache/cms-xcache/templates/deployment.yaml, incubator/cms-xcache/cms-xcache/values.yaml
-Adds new Value called `NodeName`. Allows the user deploying the chart to specify the hostname of the Kubernetes node that is desired for scheduling the cache.
-Chart 0.2.0
=> [Incubator][cms-xcache] Enable Node Selection based on Hostname

incubator/cms-xcache/cms-xcache/Chart.yaml, incubator/cms-xcache/cms-xcache/templates/deployment.yaml
Doing this with hostnames instead. Removing:
```
nodeSelector:
xcache-capable: "true"
tolerations:
- key: "special"
operator: "Exists"
effect: PreferNoSchedule
```
=> [incubator][cms-xcache] Remove old toleration and node selection (inherited from Atlas)

stable/gridftp/gridftp/Chart.yaml, stable/gridftp/gridftp/templates/deployment.yaml, stable/gridftp/gridftp/values.yaml
This patch changes the GridFTP application to use a hostname-based node selector, much like CMS XCache.
=> Fix selector

incubator/cms-xcache/cms-xcache/Chart.yaml, incubator/cms-xcache/cms-xcache/templates/deployment.yaml, incubator/cms-xcache/cms-xcache/values.yaml
Adds two values to `values.yaml`
-XCacheConfig.XCRedirectorFQDN
-XCacheConfig.XCRedirectorPort
Requires: https://github.com/opensciencegrid/docker-xcache/pull/61
=> [incubator][cms-xcache] Add Ability to configure redirector port and FQDN through chart values

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/README.md
File names for user credentials should match the Open Science Grid documentation
https://opensciencegrid.org/docs/security/user-certs/#certificate-formats
Closes #384
=> [stable][osg-hosted-ce] Update file names for user credentials within app documentation

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
Optionally uses two SLATE Volumes to persist files across restarts of the application. 
-/var/lib/condor-ce
-/var/log/condor-ce
Adds two new chart values:
```
Persistence:
LogVolume: null 
LibCondorCeVolume: null
```
=> [osg-hosted-ce][stable] Add persistence for /var/lib/condor-ce and /var/log/condor-ce

incubator/open-ondemand/open-ondemand/Chart.yaml, incubator/open-ondemand/open-ondemand/templates/deployment.yaml, incubator/open-ondemand/open-ondemand/templates/desktop-host-configmap.yaml
OnDemand was missing an "if desktobEnable=true" statement that makes the container search for a missing volume when values.yaml has "desktopEnable: false". With this change desktop features can be properly disabled.
Also adding some extra config for the desktop application.
=> Fix templating issue with Open OnDemand

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
Summary of changes:
- Log rotation
- Option to restrict outbound traffic
- Making CPU requests configurable
- Use port 3401 on the target host as a monitoring port.
- Option to disable logging
- Pull 'release' instead of 'fresh OSG Frontier Squid docker image
=> Frontier squid log n oacl

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
Updated description for the ephemeral storage request and limit, and changed the default values and logic accordingly. Cachsize now gets added to whatever the user requests for container storage.
=> Frontier squid storage

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
These changes give the user options to:
- Use the host local timezone for container and log messages
- Use host path log directory to retain log messages when the squid pod restarts
=> Frontier squid enhancement1

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
Making the squid's maximum_object_size_in_memory variable configurable
=> Squid enhancement2

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
We need to make SLATE volume support work harmoniously with hostPath support.
Does this change resolve that? Are there any other issues? 
Wondering if the Instance name is really needed.. do multiple squid workers share a cache or build their own cache? I would assume the former.
=> Need to harmonize SLATE volumes w/ HostPath 

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
1.  We definitely want recreate when using PVCs since we don't want
two sets of daemons using the same dirs, concurrently
2.  Operators have to 'slate instance delete' first anyway so
RollingUpdate doesn't actually do anything
=> Use "Recreate" instead of "RollingUpdate" for CEs

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/service.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
I opted to drop the label entirely instead of using `{{ template "osg-hosted-ce.chart" . }}` since that'd just duplicate the `app` label
=> Incubator Hosted CE: drop chart label

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/pvc.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/service.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
Removed the problematic "Chart" label from the squid chart
Added new ImageTag parameter, with a default of 'release' so nothing changes for current instances. But new instances can select an alternate tag.
=> Squid image selection

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
We noticed a site with 3.3k sandbox dirs on the remote login node,
most of which were stale. Job removal should eventually clean up the
sandbox dirs so let's extend the termination time to ensure HTCondor
can do its job.
=> Allow HTCondor-CE more time to clean up after itself

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
I'm not sure if leaving out the `path` is legal but we don't really need to rename the secret item names
=> Some quick changes for dir-mounted cert/key

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
We either set up a log-volume as a PVC if specified or as an emptyDir
if we're using the HTTPLogger
=> Fixup log-volume setup and reference

incubator/telegraf/telegraf/Chart.yaml, incubator/telegraf/telegraf/README.md, incubator/telegraf/telegraf/templates/configmap.yaml, incubator/telegraf/telegraf/templates/deployment.yaml, incubator/telegraf/telegraf/values.yaml
Updates the Telegraf monitoring application to expose two additional values.
Also removes the GRNOC password from the `values.yaml` file and uses a SLATE secret instead.
=> Make changes to Telegraf application

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
Needs https://github.com/opensciencegrid/docker-compute-entrypoint/pull/49 to do anything useful but should be safe without it
=> Allow operators to specify an SSH certificate secret (SOFTWARE-4850)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
The `hosted-ce` container takes `/etc/osg/ssh_known_hosts` and dumps it into the appropriate locations: https://github.com/opensciencegrid/docker-compute-entrypoint/pull/53
=> Add the ability to predefine known_hosts (SOFTWARE-4896)

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
We have changed the OSG Frontier Squid application to use the OSG Harbor Instance (aka OSG Hub)
=> Squid to use OSG Hub

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
(SOFTWARE-5202)
The previous solution was to depend on the SSH config and drop the
port consideration. The remote_gahp now supports <FQDN>:<PORT> but
defaults to 22 if the port isn't specified
=> Use built-in remote_gahp support for non-standard SSH port

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml, stable/osg-frontier-squid/osg-frontier-squid/values.yaml
The proposed change uses Helm's templating language to collapse down multi-CPU options down into a single "CPU" option that will automatically set up the Squid child workers and pin them as appropriate.
=> Collapse multi-CPU options down to a single parameter

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
The cache memory spec will now consider how many CPUs were requested and divide accordingly. Squid passes the `cache_mem` memory value to each child process it manages in multi-core mode. 
For some reason this has to happen in two places. Need to investigate if this is redundant or not.
=> Cache memory is now aware of the CPUs requested

stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
We were not previously requesting/limiting memory usage. We see on some squids that they exit with Error 137, which is evidently OOM according to the internet.
I've tested this with the default values.yaml and I see:
```yaml
resources:
requests:
cpu: 1
memory: '4096Mi'
ephemeral-storage: 16537Mi
limits:
cpu: 2
memory: '8192Mi'
ephemeral-storage: 21537Mi
```
If I render the template with `CacheDirOnHost: True`, I get:
``` yaml   
resources:
requests:
cpu: 1
memory: '4096Mi'
ephemeral-storage: 7000Mi
limits:
cpu: 2
memory: '8192Mi'
ephemeral-storage: 12000Mi
```
So I think things are ~working as expected, since we add an additional bit of extra disk  for the cache itself on top of the ephemeral storage request if CacheDirOnHost is false (default), and go with only the values specified in …
=> Clean up cpu/disk requests, add mem requests

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
Sometimes, for whatever reason, the Heartbeat liveness probe will fail. This isn't because Squid has failed, necessarily - just that the heartbeat script can't reach the other side. Replace the liveness probe with a cron- we don't want to depend on the availability of a remote server in order for Squid to run. Having it be a cron makes the probe more passive.
=> Replace the liveness probe with a cron. 

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml, stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
`heartbeat.sh` is currently showing as mode 700 but we need it to be 755 to be executed by the squid user.
=> Fix Squid heartbeat script mode

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
The underlying HTCondor version in the OSG containers does not support
the GSI (and by extension VOMS) mappings
Corresponding PR for the container https://github.com/opensciencegrid/docker-compute-entrypoint/pull/68
=> Remove VOMS/GSI user mappings (SOFTWARE-5252)

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml, incubator/osg-hosted-ce/osg-hosted-ce/templates/service.yaml, incubator/osg-hosted-ce/osg-hosted-ce/values.yaml
- Merge changes from stable/osg-hosted-ce again
- Modify the deployment and service templates such that we only open port 80 if the values don't specify a host cert or certkey
=> osg-hosted-ce: merge stable, close port 80 if we don't need it for Let's Encrypt (incubator)

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml, stable/osg-hosted-ce/osg-hosted-ce/templates/service.yaml, stable/osg-hosted-ce/osg-hosted-ce/values.yaml
We're moving some of our hosts to a separate VLAN and need to be able to specify an annotation to make sure MetalLB allocates an IP on the same VLAN that the pod is running on.
=> Add a way to provide arbitrary annotations to the Service of an osg-hosted-ce
