slateci/slate-catalog

incubator/datadog/.helmignore
incubator/datadog/Chart.yaml
incubator/datadog/OWNERS
incubator/datadog/README.md
incubator/datadog/requirements.lock
incubator/datadog/requirements.yaml
incubator/datadog/templates/NOTES.txt
incubator/datadog/templates/_helpers.tpl
incubator/datadog/templates/apikey-secret.yaml
incubator/datadog/templates/checksd-configmap.yaml
incubator/datadog/templates/clusterrole.yaml
incubator/datadog/templates/clusterrolebinding.yaml
incubator/datadog/templates/confd-configmap.yaml
incubator/datadog/templates/daemonset.yaml
incubator/datadog/templates/deployment.yaml
incubator/datadog/templates/service.yaml
incubator/datadog/templates/serviceaccount.yaml
incubator/datadog/values.yaml

Datadog's original helm chart sourced from here: https://github.com/helm/charts/tree/master/stable/datadog
I should have standardized the helm chart so it's fitting for SLATE.

Added Datadog application's helm chart to incubator directory.

---

incubator/condor-ce/condor-ce/Chart.yaml
incubator/condor-ce/condor-ce/templates/deployment.yaml

Followed Lincoln's example to add Downward API for the node name.

Add node name

---

incubator/condor-ce/condor-ce/Chart.yaml
incubator/condor-ce/condor-ce/templates/deployment.yaml

Updated command to include both the symlink and the Entrypoint.

change command to include EntryPoint

---

incubator/gridftp/gridftp/Chart.yaml
incubator/gridftp/gridftp/templates/deployment.yaml
incubator/gridftp/gridftp/values.yaml

As summarized. May require changes.

Add DFS support to SLATE GridFTP App

---

incubator/gridftp/gridftp/Chart.yaml
incubator/gridftp/gridftp/README.md
incubator/gridftp/gridftp/templates/deployment.yaml
incubator/gridftp/gridftp/values.yaml

Just renamed DFS to Internal/External, removed what appears to be nonfunctional parts of the Values file.

Minor aesthetic changes

---

stable/htcondor/htcondor/Chart.yaml
stable/htcondor/htcondor/README.md

Fix `slate app install` syntax under usage

Update usage section

---

stable/gridftp/gridftp/Chart.yaml
stable/gridftp/gridftp/templates/deployment.yaml

Make backend storage paths optional

Gridftp optional storage

---

incubator/login-node/login-node/Chart.yaml
incubator/login-node/login-node/templates/deployment.yaml

update image pull policy

---

incubator/login-node/images/container-login-node/Dockerfile
incubator/login-node/images/container-login-node/container-files/config/bootstrap.sh
incubator/login-node/images/container-login-node/container-files/etc/ssh/sshd_config
incubator/login-node/login-node/Chart.yaml
incubator/login-node/login-node/templates/deployment.yaml
incubator/login-node/login-node/values.yaml

First steps for LDAP integration.

add ldap support to the base login node

---

stable/faucet/faucet/Chart.yaml
stable/faucet/faucet/templates/deployment.yaml
stable/perfsonar-testpoint/perfsonar-testpoint/Chart.yaml
stable/perfsonar-testpoint/perfsonar-testpoint/templates/deployment.yaml

Update API Version in deployment specs for faucet and the perfsonar-testpoint.

Fix api versions

---

stable/grafana/grafana/Chart.yaml
stable/grafana/grafana/templates/deployment.yaml

Fix grafana for compatibility with Kubernetes 1.16

---

stable/minio/minio/Chart.yaml
stable/minio/minio/values.yaml

I thought we had done this already, but apparently we missed it somehow.

Remove unused image settings

---

stable/minio/images/minio/Dockerfile

Using the latest upstream Dockerfile fixes the build issues for me.

Merge upstream image changes

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Set developer env var string

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

https://opensciencegrid.atlassian.net/browse/SOFTWARE-3921
Default values are based off of the VO/user mappings that OSG Ops/Management have decided on (cc @matyasselmeci )

Add default VO-user mappings for OSG Hosted CEs (SOFTWARE-3921)

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

https://github.com/opensciencegrid/docker-hosted-ce/pull/14

Support container remote host setup

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

We decided to remove CustomizationScript here:
https://github.com/slateci/slate-catalog/pull/197/

Remove missed reference to CustomizationScript

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

A couple of value file simplifications and fixups

Simplify hosted CE values

---

stable/minio/minio/Chart.yaml
stable/minio/minio/templates/deployment.yaml

Fix Minio deployment deprecated Kubernetes API version

---

stable/minio/minio/Chart.yaml
stable/minio/minio/templates/statefulset.yaml

Update Minio API version to apps/v1

---

stable/perfsonar-testpoint/perfsonar-testpoint/Chart.yaml
stable/perfsonar-testpoint/perfsonar-testpoint/templates/deployment.yaml

Need to nest the `privileged: true` under `securityContext`

Fix Perfsonar Deployment for apps/v1

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

The first step in greatly simplifying the values file and CE user creation in the container.

Only support single remote (SOFTWARE-3960)

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/README.md

Bring README instructions fully up to date with latest configurations

Fully update osg-hosted-ce README

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

Remove all site specific details from values

Scrub osg-hosted-ce default values

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/README.md
stable/osg-hosted-ce/osg-hosted-ce/templates/_helpers.tpl
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/service.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

SLATE osg-hosted-ce 1.0 stable release

Promote Osg-Hosted-Ce to stable catalog

---

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/README.md
incubator/jupyter-notebook/jupyter-notebook/templates/_helpers.tpl
incubator/jupyter-notebook/jupyter-notebook/templates/deployment.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/ingress.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/service.yaml
incubator/jupyter-notebook/jupyter-notebook/values.yaml

Hi Mitchell,
Can you merge this to master?
Thanks!

Jupyter notebook patch1

---

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/README.md
incubator/jupyter-notebook/jupyter-notebook/templates/service.yaml

Can you please review and merge if no changes are necessary?
Thanks!
-M

Added some labels to the service resource

---

incubator/condor-submit/condor-submit/Chart.yaml
incubator/condor-submit/condor-submit/templates/deployment.yaml

Need to wrap provisioner-configuration in an if statement.

Condor submit patch

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Incorporates https://github.com/slateci/slate-catalog/pull/232

Fix HostedCE Certificate Volume Name

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

This shouldn't really break anything as-is but it's nice to keep things straight

ensure HostedCE init container is using pull always

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Specify the exact Hosted CE image to use

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/README.md
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

-Clarify that Memory is per node
-Squid Location can be an IP
-Add command example for creating Certificate as a SLATE secret

HostedCe Documentation Updates

---

stable/perfsonar-testpoint/perfsonar-testpoint/Chart.yaml
stable/perfsonar-testpoint/perfsonar-testpoint/templates/deployment.yaml

Small updates to perfSONAR:
-Update container version
-Always pull container image

Perfsonar minor patch 1.2

---

incubator/open-science-ce/open-science-ce/Chart.yaml
incubator/open-science-ce/open-science-ce/templates/_helpers.tpl
incubator/open-science-ce/open-science-ce/templates/configmap.yaml
incubator/open-science-ce/open-science-ce/templates/deployment.yaml
incubator/open-science-ce/open-science-ce/templates/service.yaml
incubator/open-science-ce/open-science-ce/values.yaml

An unholy combination of the `hosted-ce` and `condor-submit` charts with a first pass of stripping out the unnecessary bits. Installs ok locally with `helm install...`.

Initial Open Science CE app

---

stable/globus-connect-v4/globus-connect-v4/Chart.yaml
stable/globus-connect-v4/globus-connect-v4/templates/configmap.yaml
stable/globus-connect-v4/globus-connect-v4/values.yaml
stable/globus-connect-v4/images/globus-connect-v4/Dockerfile
stable/globus-connect-v4/images/globus-connect-v4/image_nametag
stable/globus-connect-v4/images/globus-connect-v4/supervisord.conf
stable/globus-connect-v4/images/globus-connect-v4/supervisord_startup.sh

This is a general change to make the Globus config a bit more inline with what we do for other stuff.
This lets us make the ports configurable for the GridFTP and MyProxy services, and then also sets the stage for possibly putting Globus behind a load balancer.

Globus improvements

---

incubator/open-science-ce/open-science-ce/Chart.yaml
incubator/open-science-ce/open-science-ce/templates/configmap.yaml

We talked this over with the ENMR folks and we decided to re-disable job retries

Disable job retries again

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

https://opensciencegrid.atlassian.net/browse/SOFTWARE-4122

Transition to using the stable Hosted CE container image

---

incubator/redis/redis/Chart.yaml
incubator/redis/redis/README.md

updated README.md to reflect slate procedure

---

incubator/redis/redis/Chart.yaml
incubator/redis/redis/README.md
incubator/redis/redis/values.yaml

README also updated to show yaml creation before installation

missing 'd' in Enabled: false in values.yaml is added back

---

incubator/jupyter-notebook/images/jupyter-condor/Dockerfile
incubator/jupyter-notebook/images/jupyter-condor/container-files/etc/supervisor/conf.d/supervisord.conf
incubator/jupyter-notebook/images/jupyter-condor/fix-permissions
incubator/jupyter-notebook/images/jupyter-condor/image_nametag
incubator/jupyter-notebook/images/jupyter-condor/jupyter_notebook_config.py
incubator/jupyter-notebook/images/jupyter-condor/start-notebook.sh
incubator/jupyter-notebook/images/jupyter-condor/start-singleuser.sh
incubator/jupyter-notebook/images/jupyter-condor/start.sh
incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/configmap.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/deployment.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/requirements.yaml

Rebasing the chart on centos 7 and adding health checks to restart pod when the user manually shutdown the application resulting in the application being inaccessible and pod still appears healthy to K8s.
If someone can take a look and give some feedback or approve, I'd appreciate it.
Thanks!

Jupyter condor centos7

---

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/configmap.yaml

a patch to fix a problem with ssh key authentication. Please approve and merge if there are no concerns or questions about this.
Thanks!

Jupyter condor centos7 patch1

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

https://opensciencegrid.atlassian.net/browse/SOFTWARE-4165

Add the ability to specify which hosted-ce image tag to use

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

- https://opensciencegrid.atlassian.net/browse/SOFTWARE-4095
- https://github.com/opensciencegrid/docker-hosted-ce/pull/63

Add ability to specify remote bosco installation dir

---

stable/stashcache/stashcache/Chart.yaml
stable/stashcache/stashcache/templates/deployment.yaml
stable/stashcache/stashcache/values.yaml

I'd like to be able to specify the image tag in the same manner as the HostedCE. This follows the same convention used there.

Stashcache tag

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml

https://opensciencegrid.atlassian.net/browse/SOFTWARE-4227

Ensure that Bosco path variables are absolute (SOFTWARE-4227)

---

incubator/condor-manager/condor-manager/Chart.yaml
incubator/condor-manager/images/condor-manager/Dockerfile
stable/minio/images/minio/Dockerfile
stable/minio/minio/Chart.yaml

Patching the condor-manager chart. condor-8.9.5 is no longer available so we're changing that to the latest condor available from the org-upcoming repo.
Please review and approve if it looks good.
Thanks!

Condor manager patch

---

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/service.yaml
incubator/jupyter-notebook/jupyter-notebook/values.yaml

this is so we can expose a range of ports for things like Parsl to do communication

added lowport/highport to Jupyter 

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

https://opensciencegrid.atlassian.net/browse/SOFTWARE-4278

Add ability to set up ITB CE without testing certificates

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Ok, apologies I missed this one in the review for @brianhlin ...

Fix secret YAML syntax.

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml

FYI @bbockelm @jdost321 @mmascher @jeffreynpeterson

Make SLATE Hosted CEs easily identifiable in the central collector

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml

Should fix some pain that Edgar is running into with his Expanse CE

Quit overriding WN PATH

---

incubator/telegraf/telegraf/Chart.yaml
incubator/telegraf/telegraf/README.md
incubator/telegraf/telegraf/templates/_helpers.tpl
incubator/telegraf/telegraf/templates/configmap.yaml
incubator/telegraf/telegraf/templates/deployment.yaml
incubator/telegraf/telegraf/templates/service.yaml
incubator/telegraf/telegraf/values.yaml

Hi, I have been working on this Telegraf monitoring application and would like to add it to the development/incubator catalog. Let me know if any changes need to be made. Thanks!

Add telegraf application to incubator

---

incubator/telegraf/telegraf/Chart.yaml
incubator/telegraf/telegraf/README.md
incubator/telegraf/telegraf/templates/configmap.yaml
incubator/telegraf/telegraf/values.yaml

Updated the parameters exposed in the values.yaml config for the Telegraf monitoring application.

Adjust exposed parameters in Telegraf application

---

stable/xcache/xcache/Chart.yaml
stable/xcache/xcache/templates/deployment.yaml
stable/xcache/xcache/values.yaml

updateCRIC change name and location.

to reflect changes in the base osg image

---

incubator/telegraf/telegraf/Chart.yaml
incubator/telegraf/telegraf/README.md
incubator/telegraf/telegraf/templates/configmap.yaml
incubator/telegraf/telegraf/values.yaml

Modified the exposed parameters in values.yaml, updated configuration to properly send data to GRNOC database.

Updated Telegraf application

---

incubator/cms-xcache/cms-xcache/Chart.yaml
incubator/cms-xcache/cms-xcache/templates/configmap.yaml
incubator/cms-xcache/cms-xcache/templates/deployment.yaml
incubator/cms-xcache/cms-xcache/templates/service.yaml
incubator/cms-xcache/cms-xcache/values.yaml

Adds SLATE optional sidecar logging as specified in
https://slateci.io/blog/slate-logging-jan-2020.html

[incubator][cms-xcache] Add optional sidecar logging

---

incubator/cms-xcache/cms-xcache/Chart.yaml
incubator/cms-xcache/cms-xcache/templates/service.yaml

Merge services for logging and xrootd into the same service object within Kubernetes.

[incubator][cms-xcache]

---

incubator/fts3/fts3/Chart.yaml
incubator/fts3/fts3/templates/deployment.yaml
incubator/fts3/fts3/templates/service.yaml
incubator/fts3/images/fts3/Dockerfile
incubator/fts3/images/fts3/README.md
incubator/fts3/images/fts3/crontab
incubator/fts3/images/fts3/docker-entrypoint.sh
incubator/fts3/images/fts3/fts-diff-4.0.1.sql
incubator/fts3/images/fts3/fts-msg-monitoring.conf
incubator/fts3/images/fts3/fts3config
incubator/fts3/images/fts3/image_nametag
incubator/fts3/images/fts3/supervisord.conf

- copy the contents of the container-fts3 repo into slate-catalog/incubator/fts3/images/fts3
- modify deployment.yml

add folder images/ into fts3

---

incubator/cms-xcache/cms-xcache/Chart.yaml
incubator/cms-xcache/cms-xcache/templates/deployment.yaml

Need to mount multiple sub directories.

[incubator][cms-xcache] Expand logging mounts

---

incubator/open-science-ce/open-science-ce/Chart.yaml
incubator/open-science-ce/open-science-ce/templates/configmap.yaml

This prevented jobs from running out in the OSG

Remove old config no longer used by IDTOKEN-based authN

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

RepoNeedsPrivKey is no longer used in the default YAML anyway

Use the same if statements as the volume creation above

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

Enable users to select a specific node for scheduling.

[stable][osg-hosted-ce] Add node affinity via hostname

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
stable/osg-frontier-squid/osg-frontier-squid/values.yaml

Please review and let me know how those changes look.

Normalizing squid config against OSG upstream - issue #435

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml
stable/osg-frontier-squid/osg-frontier-squid/values.yaml

added an option to truncate log file every 2 min.

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml

just forgotten things.

---

incubator/perfsonar-checker/perfsonar-checker/Chart.yaml
incubator/perfsonar-checker/perfsonar-checker/README.md
incubator/perfsonar-checker/perfsonar-checker/templates/configmap.yaml

A couple of fixes to the chart

Perfsonar-checker

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/README.md
stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
stable/osg-frontier-squid/osg-frontier-squid/values.yaml

Add a parameter to allow Squid to use a HostPath for disk cache

Squid hostpath cache

---

incubator/condor-manager/condor-manager/Chart.yaml
incubator/condor-manager/images/condor-manager/Dockerfile
incubator/condor-submit/condor-submit/Chart.yaml
incubator/condor-submit/images/condor-submit/Dockerfile
stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/README.md

This change is made to address the below open ticket
https://github.com/slateci/slate-catalog/issues/377
The change has been tested externally. But if someone is familiar with this chart and can easily test this change with a Hosted-CE deployment to confirm it resolves the reported problem, that would great.
Thanks.

Addressing ticket# 377

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/README.md
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

in prep for scitokens update in incubator

bring incubator up to date with stable (SOFTWARE-4564)

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml

update configmap.yaml for 50-slate-scitokens.conf (SOFTWARE-4564)

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

@brianhlin totally vouches for this... I think.

add mount for 50-slate-scitokens.conf (SOFTWARE-4564)

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

in collaboration with @brianhlin

move incubator/osg-hosted-ce to stable (SOFTWARE-4564)

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml
stable/osg-frontier-squid/osg-frontier-squid/values.yaml

added new option for minimum object size on disk cache or disabling itt entirely

new options for squid

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml

Apply change from #489 to the osg-hosted-ce chart in the incubator

Escape periods for SCITOKENS regex (incubator version)

---

stable/cms-xcache/cms-xcache/Chart.yaml
stable/cms-xcache/cms-xcache/templates/deployment.yaml

XCache / OSG upstream

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Don't use subPath for LE certs (incubator)

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml

Either as a user-specified PVC or an emptyDir
https://github.com/slateci/slate-catalog/blob/9ca31b73ba6e91f55dd80749b7bb4c187e89c4d2/stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml#L105-L112

log-volume is always available (SOFTWARE-4423)

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

As this is the one blessed by OSG

Use the OSG 'release' tag

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml

This may finally be the working configuration.

changed to setoptionparameter to try to get the diskless thing working

---

stable/globus-connect-v4/globus-connect-v4/Chart.yaml
stable/globus-connect-v4/globus-connect-v4/templates/deployment.yaml

[stable][globus-connect-v4] Fix SLATE instance_id label Globus

---

incubator/jupyter-notebook/jupyter-notebook/Chart.yaml
incubator/jupyter-notebook/jupyter-notebook/templates/deployment.yaml
incubator/jupyter-notebook/jupyter-notebook/values.yaml

Added GPU resource request configuration to deployment.yaml and values.yaml
Incremented version in Chart.yaml

Added GPU resource request configuration

---

incubator/open-ondemand/open-ondemand/Chart.yaml
incubator/open-ondemand/open-ondemand/TODO.md

Cherry-picked Pierce's TODO and bumped the version appropriately for this chart.

Open ondemand fixup1

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

Add a flag to allow operators to debug Hosted CE startup

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

https://github.com/opensciencegrid/docker-compute-entrypoint/pull/56

Choose a more descriptive env var/values name (SOFTWARE-4981)

---

stable/osg-frontier-squid/osg-frontier-squid/Chart.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/configmap.yaml
stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml
stable/osg-frontier-squid/osg-frontier-squid/values.yaml

This PR adds heartbeats for the ATLAS alarm & alert service for Squid.

add AAAS Heartbeat and configuration

---

incubator/osg-hosted-ce/osg-hosted-ce/Chart.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
incubator/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
incubator/osg-hosted-ce/osg-hosted-ce/values.yaml

It was many versions behind; I literally just copied everything over.

Bring incubator/osg-hosted-ce up-to-date with stable/osg-hosted-ce

---

incubator/fts3/images/fts3/Dockerfile

Changed base image tag to "el7-fresh".

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/deployment.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

Also includes a bonus commit renaming config files that was requested a little while back.

Add the ability for operators to specify additional osg-configure configuration (SOFTWARE-4462)

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

The container forces the same user as expected at the login host
destination

Clarify expected ProxyJump formatting

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/values.yaml

The implementation from #533 loops over a map not a list of maps

Fix documentation of the new NodeSelection stanza

---

stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
stable/osg-hosted-ce/osg-hosted-ce/templates/service.yaml

@matyasselmeci how's this look to you?

Hosted CE: close port 80 except for (SOFTWARE-5314)

---

stable/nginx/nginx/Chart.yaml
stable/nginx/nginx/templates/service.yaml

Updated nginx ingress api version.
